# Generated by Django 3.1.4 on 2020-12-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
