# Generated by Django 3.1.4 on 2021-01-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20201231_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='remind_me_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
