# Generated by Django 3.1.4 on 2021-01-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todoitem_remind_me_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Critically important'), (2, 'Very important'), (3, 'Highly important'), (4, 'Medium important'), (5, 'Low important')], default=5),
        ),
    ]
